(when (memq system-type '(darwin))
  (concat
   (propertize "                                                    \n")
   (propertize "                             'c.                    \n" 'face `(:foreground "green"))
   (propertize "                          ,xNMM.                    \n" 'face `(:foreground "green"))
   (propertize "                        .OMMMMo                     \n" 'face `(:foreground "green"))
   (propertize "                        OMMM0,                      \n" 'face `(:foreground "green"))
   (propertize "              .;loddo:' loolloddol;.                \n" 'face `(:foreground "green"))
   (propertize "            cKMMMMMMMMMMNWMMMMMMMMMM0:              \n" 'face `(:foreground "green"))
   (propertize "          .KMMMMMMMMMMMMMMMMMMMMMMMWd.              \n" 'face `(:foreground "yellow"))
   (propertize "          XMMMMMMMMMMMMMMMMMMMMMMMX.                \n" 'face `(:foreground "yellow"))
   (propertize "        ;MMMMMMMMMMMMMMMMMMMMMMMM:                  \n" 'face `(:foreground "red"))
   (propertize "        :MMMMMMMMMMMMMMMMMMMMMMMM:                  \n" 'face `(:foreground "red"))
   (propertize "        .MMMMMMMMMMMMMMMMMMMMMMMMX.                 \n" 'face `(:foreground "red"))
   (propertize "         kMMMMMMMMMMMMMMMMMMMMMMMMWd.               \n" 'face `(:foreground "red"))
   (propertize "          .XMMMMMMMMMMMMMMMMMMMMMMMMMMk             \n" 'face `(:foreground "magenta"))
   (propertize "           .XMMMMMMMMMMMMMMMMMMMMMMMMK.             \n" 'face `(:foreground "magenta"))
   (propertize "             kMMMMMMMMMMMMMMMMMMMMMMd               \n" 'face `(:foreground "blue"))
   (propertize "              ;KMMMMMMMWXXWMMMMMMMk.                \n" 'face `(:foreground "blue"))
   (propertize "                .cooc,.    .,coo:.                  \n" 'face `(:foreground "blue"))
   (propertize "                                                    \n")
   (propertize "                        _/                  _/  _/  \n" 'face `(:foreground "blue"))
   (propertize "     _/_/      _/_/_/  _/_/_/      _/_/    _/  _/   \n" 'face `(:foreground "blue"))
   (propertize "  _/_/_/_/  _/_/      _/    _/  _/_/_/_/  _/  _/    \n" 'face `(:foreground "blue"))
   (propertize " _/            _/_/  _/    _/  _/        _/  _/     \n" 'face `(:foreground "blue"))
   (propertize "  _/_/_/  _/_/_/    _/    _/    _/_/_/  _/  _/      \n" 'face `(:foreground "blue"))
   (propertize "                                                    \n")
   (propertize "                                                    \n")))
